# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
# https://blog.readthedocs.com/apt-packages/
# https://github.com/readthedocs/readthedocs.org/issues/8656 - need to install wxpython from conda. Don't need it for building doc, so I'll just not install anything.

#build:
#  os: "ubuntu-20.04"
#  tools:
#    python: "3.8"
#  apt_packages:
#    - libgtk-3-dev
sphinx:
  configuration: docs/conf.py
formats: all
#python:
#  install:
#    - requirements: docs/requirements.txt
#    - method: pip
#      path: .