# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
# https://blog.readthedocs.com/apt-packages/
build:
  apt_packages:
    - libgtk-3-dev
sphinx:
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
